version: '3.8'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent_net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_storage:/data
    networks:
      - portainer_agent_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  portainer_agent_net:
    driver: overlay
    attachable: true

volumes:
  portainer_storage:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.0.200,rw,sync
      device: ":/mnt/storage-swarm-01/portainer"